@startuml
State S1
State S2
S1 -[#DD00AA]-> S2
S1 -left[#yellow]-> S3
S1 -up[#red,dashed]-> S4
S1 -right[dotted,#blue]-> S5

X1 -[dashed]-> X2
Z1 -[dotted]-> Z2
Y1 -[#blue,bold]-> Y2
@enduml

////////////////////////////

start
  state_diagram
    state
      state_name        S1
    state
      state_name        S2
    transition
      departure_state   S1
      arrow     -[#DD00AA]->
      arrival_state     S2
    transition
      departure_state   S1
      arrow     -left[#yellow]->
      arrival_state     S3
    transition
      departure_state   S1
      arrow     -up[#red,dashed]->
      arrival_state     S4
    transition
      departure_state   S1
      arrow     -right[dotted,#blue]->
      arrival_state     S5
    transition
      departure_state   X1
      arrow     -[dashed]->
      arrival_state     X2
    transition
      departure_state   Z1
      arrow     -[dotted]->
      arrival_state     Z2
    transition
      departure_state   Y1
      arrow     -[#blue,bold]->
      arrival_state     Y2
